checks:
    python:
        code_rating: true
        duplicate_code: true
filter:
    paths: ["pyof/*", "tests/*"]
build:
    environment:
        python: 3.9.12
        postgresql: false
        redis: false
    dependencies:
        override:
            - true
    tests:
        before:
            - pip install coverage
        override:
            -
                command: 'tox'
                only_if: 'tox -a | grep -q py39'
                idle_timeout: 300
                coverage:
                    file: '.coverage'
                    config_file: '.coveragerc'
                    format: 'py-cc'
            - py-scrutinizer-run
